import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateProductTagTable1786642068896 implements MigrationInterface {
    name = 'CreateProductTagTable1786642068896'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storeId" uuid NOT NULL, "productId" uuid NOT NULL, "name" character varying NOT NULL, "sku" character varying, "barcode" character varying, "price" numeric(10,2) NOT NULL, "compareAtPrice" numeric(10,2), "costPrice" numeric(10,2), "quantity" integer NOT NULL DEFAULT '0', "weight" numeric(10,2), "option1" character varying NOT NULL, "option2" character varying, "option3" character varying, "imageId" uuid, "position" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CHK_01b67a341ac9a63d7bffec0f6c" CHECK (
  "compareAtPrice" IS NULL 
  OR "compareAtPrice" >= "price"
), CONSTRAINT "CHK_fc020f1393d076ae267deeac48" CHECK ("quantity" >= 0), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc02f60ce49e3f541a1352e124" ON "product_variants"  ("storeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f515690c571a03400a9876600b" ON "product_variants"  ("productId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9532fcb23773164796d379a9a3" ON "product_variants"  ("storeId", "sku") `);
        await queryRunner.query(`CREATE TABLE "product_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "name" character varying(100) NOT NULL, "values" jsonb NOT NULL, "position" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3916b02fb43aa725f8167c718e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_96d8f73d05e681974c07b99ee5" ON "product_options"  ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_85b4627a5293171f96b0374cdc" ON "product_options"  ("productId", "position") `);
        await queryRunner.query(`CREATE TABLE "sub_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parentId" uuid, "storeId" uuid, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "image" character varying, "position" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a8e238bdcdc2df32eac3c8edc9e" UNIQUE ("slug"), CONSTRAINT "PK_f319b046685c0e07287e76c5ab1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9bd46d8ba00a8b2a1b431c70bb" ON "sub_categories"  ("parentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed691f44475a125224a3b2c25c" ON "sub_categories"  ("storeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dc55b12a308376c9aaa9ebad88" ON "sub_categories"  ("storeId", "slug") `);
        await queryRunner.query(`CREATE TABLE "product_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "categoryId" uuid NOT NULL, CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6156a79599e274ee9d83b1de13" ON "product_categories"  ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdef3adba0c284fd103d0fd369" ON "product_categories"  ("categoryId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e65c1adebf00d61f1c84a4f395" ON "product_categories"  ("productId", "categoryId") `);
        await queryRunner.query(`CREATE TABLE "product_tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storeId" uuid NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(120) NOT NULL, CONSTRAINT "PK_e96bca3cd7a592009f2c9dc6f3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_42791c94e21a912766ce196e26" ON "product_tags"  ("storeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_322630bd55217020bc2091a210" ON "product_tags"  ("storeId", "slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_369baa787f8ae9b31fb7854078" ON "product_tags"  ("storeId", "name") `);
        await queryRunner.query(`CREATE TABLE "product_tag_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "tagId" uuid NOT NULL, CONSTRAINT "PK_81bdc9e2e85b0d370b3df6b6541" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8899d1982d58153b20afe6506e" ON "product_tag_assignments"  ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd4ce62db747fe6699546216a2" ON "product_tag_assignments"  ("tagId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_42c01f48e18b165bd730dd3da4" ON "product_tag_assignments"  ("productId", "tagId") `);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "stock"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "shortDescription" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "costPrice" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "barcode" character varying`);
        await queryRunner.query(`ALTER TABLE "products" ADD "allowBackorders" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "products" ADD "quantity" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "products" ADD "lowStockThreshold" integer NOT NULL DEFAULT '10'`);
        await queryRunner.query(`ALTER TABLE "products" ADD "weight" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "dimensions" jsonb`);
        await queryRunner.query(`ALTER TABLE "products" ADD "hasVariants" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "products" ADD "isFeatured" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "products" ADD "isDigital" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "products" ADD "metaTitle" character varying(70)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "metaDescription" character varying(160)`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "url"`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "url" character varying NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "name" character varying(200)`);
        await queryRunner.query(`UPDATE "products" SET "name" = COALESCE("slug", 'Untitled Product') WHERE "name" IS NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "UQ_464f927ae360106b783ed0b4106"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "description" character varying(5000)`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying(100)`);
        await queryRunner.query(`CREATE INDEX "IDX_41ff0c3ddf82ba1d3fe902d2fd" ON "product_images"  ("productId", "position") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_41c563850936fd9b15fdd171d9" ON "product_images"  ("productId", "isPrimary") WHERE "isPrimary" = true`);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products"  ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_58075ba759b7738eb2eac5a9af" ON "products"  ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_af4d44ad0bc044be7d5ad4ee92" ON "products"  ("storeId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7182963fff52eec3a4964bd7be" ON "products"  ("storeId", "sku") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9844b96a2b5b3620eee675f805" ON "products"  ("storeId", "slug") `);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "CHK_fbcf76ce1ad05a5e958545c354" CHECK ("weight" IS NULL OR "weight" >= 0)`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "CHK_91c5a0d3e7f40b4e64f71b917e" CHECK ("lowStockThreshold" >= 0)`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "CHK_4116e455ddd76b4c0ce10dcf48" CHECK ("quantity" >= 0)`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "CHK_2192f21fd27696cf2d00a1a06f" CHECK ("costPrice" IS NULL OR "costPrice" >= 0)`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "CHK_b6dc9e7b6b425a9601050db1bb" CHECK ("compareAtPrice" IS NULL OR "compareAtPrice" >= "price")`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "CHK_90ac64027434b412e08988bcac" CHECK ("price" >= 0)`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_880be96629597e53596e18aa137" FOREIGN KEY ("imageId") REFERENCES "product_images"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_options" ADD CONSTRAINT "FK_96d8f73d05e681974c07b99ee5d" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD CONSTRAINT "FK_9bd46d8ba00a8b2a1b431c70bb7" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_categories" ADD CONSTRAINT "FK_ed691f44475a125224a3b2c25c0" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_6156a79599e274ee9d83b1de139" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_fdef3adba0c284fd103d0fd3697" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tags" ADD CONSTRAINT "FK_42791c94e21a912766ce196e26e" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tag_assignments" ADD CONSTRAINT "FK_8899d1982d58153b20afe6506ef" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tag_assignments" ADD CONSTRAINT "FK_fd4ce62db747fe6699546216a2e" FOREIGN KEY ("tagId") REFERENCES "product_tags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_tag_assignments" DROP CONSTRAINT "FK_fd4ce62db747fe6699546216a2e"`);
        await queryRunner.query(`ALTER TABLE "product_tag_assignments" DROP CONSTRAINT "FK_8899d1982d58153b20afe6506ef"`);
        await queryRunner.query(`ALTER TABLE "product_tags" DROP CONSTRAINT "FK_42791c94e21a912766ce196e26e"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_fdef3adba0c284fd103d0fd3697"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_6156a79599e274ee9d83b1de139"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP CONSTRAINT "FK_ed691f44475a125224a3b2c25c0"`);
        await queryRunner.query(`ALTER TABLE "sub_categories" DROP CONSTRAINT "FK_9bd46d8ba00a8b2a1b431c70bb7"`);
        await queryRunner.query(`ALTER TABLE "product_options" DROP CONSTRAINT "FK_96d8f73d05e681974c07b99ee5d"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_880be96629597e53596e18aa137"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "CHK_90ac64027434b412e08988bcac"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "CHK_b6dc9e7b6b425a9601050db1bb"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "CHK_2192f21fd27696cf2d00a1a06f"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "CHK_4116e455ddd76b4c0ce10dcf48"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "CHK_91c5a0d3e7f40b4e64f71b917e"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "CHK_fbcf76ce1ad05a5e958545c354"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9844b96a2b5b3620eee675f805"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7182963fff52eec3a4964bd7be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af4d44ad0bc044be7d5ad4ee92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58075ba759b7738eb2eac5a9af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41c563850936fd9b15fdd171d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41ff0c3ddf82ba1d3fe902d2fd"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku")`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products" USING btree ("name") `);
        await queryRunner.query(`ALTER TABLE "product_images" DROP COLUMN "url"`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD "url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "metaDescription"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "metaTitle"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "isDigital"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "isFeatured"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "hasVariants"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "dimensions"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "weight"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "lowStockThreshold"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "allowBackorders"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "barcode"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "costPrice"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "shortDescription"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "stock" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42c01f48e18b165bd730dd3da4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd4ce62db747fe6699546216a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8899d1982d58153b20afe6506e"`);
        await queryRunner.query(`DROP TABLE "product_tag_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_369baa787f8ae9b31fb7854078"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_322630bd55217020bc2091a210"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42791c94e21a912766ce196e26"`);
        await queryRunner.query(`DROP TABLE "product_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e65c1adebf00d61f1c84a4f395"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdef3adba0c284fd103d0fd369"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6156a79599e274ee9d83b1de13"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc55b12a308376c9aaa9ebad88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed691f44475a125224a3b2c25c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bd46d8ba00a8b2a1b431c70bb"`);
        await queryRunner.query(`DROP TABLE "sub_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85b4627a5293171f96b0374cdc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96d8f73d05e681974c07b99ee5"`);
        await queryRunner.query(`DROP TABLE "product_options"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9532fcb23773164796d379a9a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f515690c571a03400a9876600b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc02f60ce49e3f541a1352e124"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
    }

}
